import assets from "./assets";

const DATA = [
  {
    id: 1,
    name: "Bjawiya royale ",
    price: 60,
    unit: "dt/kg",
    image: assets.img02,
    creator: "Pâtisserie Le Pacha",
    creatorImg: assets.person08,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de noisettes et pistaches caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-11",
        name: "Gâteau américain Red Velvet",
        price: 4.25,
        unit: "dt/kg",
        image: assets.img30,
      },
      {
        id: "BID-12",
        name: "Ghrayba Pistache",
        price: 4.5,
        unit: "dt/kg",
        image: assets.img31,
      },
      {
        id: "BID-13",
        name: "Macarons Fraise/Franboise",
        price: 4.75,
        unit: "dt/kg",
        image: assets.img32,
      },
    ],
  },
  {
    id: 2,
    name: "Boules D'énergie(dattes)",
    price: 29.9,
    unit: "dt/kg",
    image: assets.img12,
    creator: "La Maison Gourmandise",
    creatorImg: assets.person07,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-21",
        name: "CERISE NOISETTE",
        price: 10.5,
        unit: "DT/100g",
        image: assets.maisonG03,
      },
      {
        id: "BID-22",
        name: "éclair citron",
        price: 4.5,
        unit: "dt/kg",
        image: assets.maisonG02,
      },
      {
        id: "BID-23",
        name: "ENROBÉ NOISETTE/PISTACHE/PIGNON",
        price: 19.5,
        unit: "DT/kg",
        image: assets.maisonG01,
      },
    ],
  },
  {
    id: 3,
    name: "Dattes Farcies",
    price: 80,
    unit: "dt/kg",
    image: assets.img13,
    creator: "Gourmandise by Rim Bouraoui",
    promotion: "-60%",
    creatorImg: assets.person06,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-24",
        name: " Boules de chocolat",
        price: 4.25,
        unit: "dt/kg",
        image: assets.GRim01,
      },
      {
        id: "BID-25",
        name: "Gamme Hlou Thé",
        price: 4.5,
        unit: "dt/kg",
        image: assets.GRim02,
      },
      {
        id: "BID-26",
        name: "Hlou tunisien",
        price: 4.75,
        unit: "dt/kg",
        image: assets.GRim03,
      },
    ],
  },
  {
    id: 4,
    name: "Zrir+Bsissa Noisette",
    price: 70,
    unit: "dt/kg",
    image: assets.img04,
    creator: "Konfida",
    creatorImg: assets.person05,
    ingredients: ["Miel Pur", "amandes", "Huile d'olive", "noisettes"],
    description: "Bsissa Fruits Secs de Konfida 🤗💚",
    populaires: [
      {
        id: "BID-27",
        name: "Bsissa Fruits Secs",
        price: 4.25,
        unit: "dt/kg",
        image: assets.eWL01,
      },
      {
        id: "BID-28",
        name: "Zrir Pistache",
        price: 4.5,
        unit: "dt/kg",
        image: assets.eWL02,
      },
      {
        id: "BID-29",
        name: "Fruits Secs Grillés",
        price: 4.75,
        unit: "dt/kg",
        image: assets.eWL03,
      },
    ],
  },
  {
    id: 5,
    name: "Sélection Gâteaux Traditionnels Tunisiens",
    price: 90,
    unit: "dt/kg",
    image: assets.img10,
    creator: "Madame Zarrouk",
    promotion: "-10%",
    creatorImg: assets.person01,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-11",
        name: "ochs bolbols",
        price: 4.25,
        unit: "dt/kg",
        image: assets.mz01,
      },
      {
        id: "BID-12",
        name: "Kounefa",
        price: 4.5,
        unit: "dt/kg",
        image: assets.mz02,
      },
      {
        id: "BID-13",
        name: " samsa noisette/pistache",
        price: 4.75,
        unit: "dt/kg",
        image: assets.mz03,
      },
    ],
  },

  {
    id: 6,
    name: "Kaak Warka",
    price: 57,
    unit: "dt/kg",
    image: assets.img03,
    creator: "Lamia sweets",
    promotion: "-60%",
    creatorImg: assets.person03,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-11",
        name: "Kaak Amber",
        price: 4.25,
        unit: "dt/kg",
        image: assets.DJasmin01,
      },
      {
        id: "BID-12",
        name: "Perle pistache chocolat blanc framboise",
        price: 4.5,
        unit: "dt/kg",
        image: assets.DJasmin02,
      },
      {
        id: "BID-13",
        name: "Rosie Wong",
        price: 4.75,
        unit: "dt/kg",
        image: assets.DJasmin03,
      },
    ],
  },

  {
    id: 7,
    name: "Mignardises panaché Pistache Noisettes",
    price: 140,
    unit: "dt/kg",
    image: assets.img11,
    creator: "Gourmandise by Rim Bouraoui",
    creatorImg: assets.person06,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-24",
        name: " Boules de chocolat",
        price: 4.25,
        unit: "dt/kg",
        image: assets.GRim01,
      },
      {
        id: "BID-25",
        name: "Gamme Hlou Thé",
        price: 4.5,
        unit: "dt/kg",
        image: assets.GRim02,
      },
      {
        id: "BID-26",
        name: "Hlou tunisien",
        price: 4.75,
        unit: "dt/kg",
        image: assets.GRim03,
      },
    ],
  },
  {
    id: 8,
    name: "Crocants Bourjouses",
    price: 74.99,
    unit: "dt/kg",
    image: assets.img08,
    creator: "Lamia sweets",
    promotion: "-20%",
    creatorImg: assets.person03,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-11",
        name: "Kaak Amber",
        price: 4.25,
        unit: "dt/kg",
        image: assets.DJasmin01,
      },
      {
        id: "BID-12",
        name: "Perle pistache chocolat blanc framboise",
        price: 4.5,
        unit: "dt/kg",
        image: assets.DJasmin02,
      },
      {
        id: "BID-13",
        name: "Rosie Wong",
        price: 4.75,
        unit: "dt/kg",
        image: assets.DJasmin03,
      },
    ],
  },
  {
    id: 9,
    name: "Mlabes",
    price: 57,
    unit: "dt/kg",
    image: assets.img06,
    creator: "Pâtisserie Le Pacha",
    promotion: "-60%",
    creatorImg: assets.person08,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-11",
        name: "Gâteau américain Red Velvet",
        price: 4.25,
        unit: "dt/kg",
        image: assets.img30,
      },
      {
        id: "BID-12",
        name: "Ghrayba Pistache",
        price: 4.5,
        unit: "dt/kg",
        image: assets.img31,
      },
      {
        id: "BID-13",
        name: "Macarons Fraise/Franboise",
        price: 4.75,
        unit: "dt/kg",
        image: assets.img32,
      },
    ],
  },

  {
    id: 10,
    name: "Assida Zgougou",
    price: 4.9,
    unit: "dt/tasse",
    image: assets.img05,
    creator: "Madame Jarraya",
    promotion: "-40%",
    creatorImg: assets.person02,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-11",
        name: "Zouza Noisettes",
        price: 4.25,
        unit: "dt/kg",
        image: assets.img14,
      },
      {
        id: "BID-12",
        name: "Jennifer Sia",
        price: 4.5,
        unit: "dt/kg",
        image: assets.img15,
      },
      {
        id: "BID-13",
        name: "Rosie Wong",
        price: 4.75,
        unit: "dt/kg",
        image: assets.img16,
      },
    ],
  },
  {
    id: 11,
    name: "Ghrayba Homs",
    price: 7.9,
    unit: "dt/plat",
    image: assets.img07,
    creator: "La maison gourmandises",
    creatorImg: assets.person07,
    ingredients: ["amandes", "noisettes", "sucres"],
    description:
      "Une friandise surprenante à mi-chemin entre l'Orient et l'Occident composée d'une coque croustillante de graines de sésames caramélisées fourrées d'un délicieux chocolat fondant, le tout orné de fruits secs. A servir à vos convives lors de vos réceptions ou en mignardise pour accompagner un thé ou un café.",
    populaires: [
      {
        id: "BID-21",
        name: "CERISE NOISETTE",
        price: 10.5,
        unit: "DT/100g",
        image: assets.maisonG03,
      },
      {
        id: "BID-22",
        name: "éclair citron",
        price: 4.5,
        unit: "dt/kg",
        image: assets.maisonG02,
      },
      {
        id: "BID-23",
        name: "ENROBÉ NOISETTE/PISTACHE/PIGNON",
        price: 19.5,
        unit: "DT/kg",
        image: assets.maisonG01,
      },
    ],
  },
];
export { DATA };
